export default {
  products: [
    {
      _id: '1',
      name: 'SUPERSTAR SHOES',
      category: 'Men',
      image: '/frontend/src/images/product-1.jpg',
      price: 85,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: '2',
      name: 'Stan Smith SHOES',
      category: 'Men',
      image: '/frontend/src/images/product-2.jpg',
      price: 90,
      brand: 'Adidas',
      rating: 5,
      numReviews: 51,
    },
    {
      _id: '3',
      name: 'LEGO SHOES',
      category: 'Child',
      image: '/frontend/src/images/product-3.jpg',
      price: 59,
      brand: 'Adidas',
      rating: 4,
      numReviews: 45,
    },
    {
      _id: '4',
      name: 'NMD SHOES',
      category: 'Men',
      image: '/frontend/src/images/product-4.jpg',
      price: 90,
      brand: 'Adidas',
      rating: 2.5,
      numReviews: 198,
      countInStock: 6,
    },
    {
      _id: '5',
      name: 'Achivo SHOES',
      category: 'Women',
      image: '/frontend/src/images/product-5.jpg',
      price: 90,
      brand: 'Adidas',
      rating: 3.5,
      numReviews: 89,
      countInStock: 6,
    },
    {
      _id: '6',
      name: 'Ultraboost SHOES',
      category: 'Women',
      image: '/frontend/src/images/product-6.jpg',
      price: 90,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 45,
      countInStock: 6,
    },
  ],
};
